# meta
model_name: stgan
exp_name: explo_stgan
mode: train
cuda: true
ngpu: 1

# data
dataset: explo
data_root: data/explo_tag/
crop_size: 256
image_size: 64

# model
g_conv_dim: 64
d_conv_dim: 64
d_fc_dim: 1024
g_layers: 5
d_layers: 5
shortcut_layers: 3
stu_kernel_size: 3
use_stu: true
one_more_conv: true
attrs: [thin, strong, wide, soft, disorderly, artistic, complex, playful, calm, dramatic]
checkpoint: ~

# training
batch_size: 64
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 5
thres_int: 0.5
lambda_gp: 10
lambda1: 1
lambda2: 10
lambda3: 100
max_iters: 1000000
lr_decay_iters: 800000

# steps:
summary_step: 100
sample_step: 5000
checkpoint_step: 20000